//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class DG_Tweening_Core_TweenerCore_int_int_DG_Tweening_Plugins_Options_NoOptionsWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions>), typeof(DG.Tweening.Tweener), "TweenerCore_int_int_DG_Tweening_Plugins_Options_NoOptions");
		L.RegFunction("ChangeStartValue", ChangeStartValue);
		L.RegFunction("ChangeEndValue", ChangeEndValue);
		L.RegFunction("ChangeValues", ChangeValues);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("startValue", get_startValue, set_startValue);
		L.RegVar("endValue", get_endValue, set_endValue);
		L.RegVar("changeValue", get_changeValue, set_changeValue);
		L.RegVar("plugOptions", get_plugOptions, set_plugOptions);
		L.RegVar("getter", get_getter, set_getter);
		L.RegVar("setter", get_setter, set_setter);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ChangeStartValue(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes<int>(L, 2))
			{
				DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions> obj = (DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions>)ToLua.CheckObject<DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions>>(L, 1);
				int arg0 = (int)LuaDLL.lua_tonumber(L, 2);
				DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions> o = obj.ChangeStartValue(arg0);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<object>(L, 2))
			{
				DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions> obj = (DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions>)ToLua.CheckObject<DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions>>(L, 1);
				object arg0 = ToLua.ToVarObject(L, 2);
				DG.Tweening.Tweener o = obj.ChangeStartValue(arg0);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 3 && TypeChecker.CheckTypes<int, float>(L, 2))
			{
				DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions> obj = (DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions>)ToLua.CheckObject<DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions>>(L, 1);
				int arg0 = (int)LuaDLL.lua_tonumber(L, 2);
				float arg1 = (float)LuaDLL.lua_tonumber(L, 3);
				DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions> o = obj.ChangeStartValue(arg0, arg1);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 3 && TypeChecker.CheckTypes<object, float>(L, 2))
			{
				DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions> obj = (DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions>)ToLua.CheckObject<DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions>>(L, 1);
				object arg0 = ToLua.ToVarObject(L, 2);
				float arg1 = (float)LuaDLL.lua_tonumber(L, 3);
				DG.Tweening.Tweener o = obj.ChangeStartValue(arg0, arg1);
				ToLua.PushObject(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions>.ChangeStartValue");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ChangeEndValue(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes<int>(L, 2))
			{
				DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions> obj = (DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions>)ToLua.CheckObject<DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions>>(L, 1);
				int arg0 = (int)LuaDLL.lua_tonumber(L, 2);
				DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions> o = obj.ChangeEndValue(arg0);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<object>(L, 2))
			{
				DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions> obj = (DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions>)ToLua.CheckObject<DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions>>(L, 1);
				object arg0 = ToLua.ToVarObject(L, 2);
				DG.Tweening.Tweener o = obj.ChangeEndValue(arg0);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 3 && TypeChecker.CheckTypes<int, bool>(L, 2))
			{
				DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions> obj = (DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions>)ToLua.CheckObject<DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions>>(L, 1);
				int arg0 = (int)LuaDLL.lua_tonumber(L, 2);
				bool arg1 = LuaDLL.lua_toboolean(L, 3);
				DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions> o = obj.ChangeEndValue(arg0, arg1);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 3 && TypeChecker.CheckTypes<int, float>(L, 2))
			{
				DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions> obj = (DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions>)ToLua.CheckObject<DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions>>(L, 1);
				int arg0 = (int)LuaDLL.lua_tonumber(L, 2);
				float arg1 = (float)LuaDLL.lua_tonumber(L, 3);
				DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions> o = obj.ChangeEndValue(arg0, arg1);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 3 && TypeChecker.CheckTypes<object, bool>(L, 2))
			{
				DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions> obj = (DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions>)ToLua.CheckObject<DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions>>(L, 1);
				object arg0 = ToLua.ToVarObject(L, 2);
				bool arg1 = LuaDLL.lua_toboolean(L, 3);
				DG.Tweening.Tweener o = obj.ChangeEndValue(arg0, arg1);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 3 && TypeChecker.CheckTypes<object, float>(L, 2))
			{
				DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions> obj = (DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions>)ToLua.CheckObject<DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions>>(L, 1);
				object arg0 = ToLua.ToVarObject(L, 2);
				float arg1 = (float)LuaDLL.lua_tonumber(L, 3);
				DG.Tweening.Tweener o = obj.ChangeEndValue(arg0, arg1);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 4 && TypeChecker.CheckTypes<int, float, bool>(L, 2))
			{
				DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions> obj = (DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions>)ToLua.CheckObject<DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions>>(L, 1);
				int arg0 = (int)LuaDLL.lua_tonumber(L, 2);
				float arg1 = (float)LuaDLL.lua_tonumber(L, 3);
				bool arg2 = LuaDLL.lua_toboolean(L, 4);
				DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions> o = obj.ChangeEndValue(arg0, arg1, arg2);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 4 && TypeChecker.CheckTypes<object, float, bool>(L, 2))
			{
				DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions> obj = (DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions>)ToLua.CheckObject<DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions>>(L, 1);
				object arg0 = ToLua.ToVarObject(L, 2);
				float arg1 = (float)LuaDLL.lua_tonumber(L, 3);
				bool arg2 = LuaDLL.lua_toboolean(L, 4);
				DG.Tweening.Tweener o = obj.ChangeEndValue(arg0, arg1, arg2);
				ToLua.PushObject(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions>.ChangeEndValue");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ChangeValues(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 3 && TypeChecker.CheckTypes<int, int>(L, 2))
			{
				DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions> obj = (DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions>)ToLua.CheckObject<DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions>>(L, 1);
				int arg0 = (int)LuaDLL.lua_tonumber(L, 2);
				int arg1 = (int)LuaDLL.lua_tonumber(L, 3);
				DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions> o = obj.ChangeValues(arg0, arg1);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 3 && TypeChecker.CheckTypes<object, object>(L, 2))
			{
				DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions> obj = (DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions>)ToLua.CheckObject<DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions>>(L, 1);
				object arg0 = ToLua.ToVarObject(L, 2);
				object arg1 = ToLua.ToVarObject(L, 3);
				DG.Tweening.Tweener o = obj.ChangeValues(arg0, arg1);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 4 && TypeChecker.CheckTypes<int, int, float>(L, 2))
			{
				DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions> obj = (DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions>)ToLua.CheckObject<DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions>>(L, 1);
				int arg0 = (int)LuaDLL.lua_tonumber(L, 2);
				int arg1 = (int)LuaDLL.lua_tonumber(L, 3);
				float arg2 = (float)LuaDLL.lua_tonumber(L, 4);
				DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions> o = obj.ChangeValues(arg0, arg1, arg2);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 4 && TypeChecker.CheckTypes<object, object, float>(L, 2))
			{
				DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions> obj = (DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions>)ToLua.CheckObject<DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions>>(L, 1);
				object arg0 = ToLua.ToVarObject(L, 2);
				object arg1 = ToLua.ToVarObject(L, 3);
				float arg2 = (float)LuaDLL.lua_tonumber(L, 4);
				DG.Tweening.Tweener o = obj.ChangeValues(arg0, arg1, arg2);
				ToLua.PushObject(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions>.ChangeValues");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_startValue(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions> obj = (DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions>)o;
			int ret = obj.startValue;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index startValue on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_endValue(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions> obj = (DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions>)o;
			int ret = obj.endValue;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index endValue on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_changeValue(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions> obj = (DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions>)o;
			int ret = obj.changeValue;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index changeValue on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_plugOptions(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions> obj = (DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions>)o;
			DG.Tweening.Plugins.Options.NoOptions ret = obj.plugOptions;
			ToLua.PushValue(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index plugOptions on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_getter(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions> obj = (DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions>)o;
			DG.Tweening.Core.DOGetter<int> ret = obj.getter;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index getter on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_setter(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions> obj = (DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions>)o;
			DG.Tweening.Core.DOSetter<int> ret = obj.setter;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index setter on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_startValue(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions> obj = (DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions>)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.startValue = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index startValue on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_endValue(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions> obj = (DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions>)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.endValue = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index endValue on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_changeValue(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions> obj = (DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions>)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.changeValue = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index changeValue on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_plugOptions(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions> obj = (DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions>)o;
			DG.Tweening.Plugins.Options.NoOptions arg0 = StackTraits<DG.Tweening.Plugins.Options.NoOptions>.Check(L, 2);
			obj.plugOptions = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index plugOptions on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_getter(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions> obj = (DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions>)o;
			DG.Tweening.Core.DOGetter<int> arg0 = (DG.Tweening.Core.DOGetter<int>)ToLua.CheckDelegate<DG.Tweening.Core.DOGetter<int>>(L, 2);
			obj.getter = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index getter on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_setter(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions> obj = (DG.Tweening.Core.TweenerCore<int,int,DG.Tweening.Plugins.Options.NoOptions>)o;
			DG.Tweening.Core.DOSetter<int> arg0 = (DG.Tweening.Core.DOSetter<int>)ToLua.CheckDelegate<DG.Tweening.Core.DOSetter<int>>(L, 2);
			obj.setter = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index setter on a nil value");
		}
	}
}

