//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Spine_JsonWrap
{
	public static void Register(LuaState L)
	{
		L.BeginStaticLibs("Json");
		L.RegFunction("Deserialize", Deserialize);
		L.EndStaticLibs();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Deserialize(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			System.IO.TextReader arg0 = (System.IO.TextReader)ToLua.CheckObject<System.IO.TextReader>(L, 1);
			object o = Spine.Json.Deserialize(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

