//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Spine_Unity_MeshRendererBuffers_SmartMeshWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Spine.Unity.MeshRendererBuffers.SmartMesh), typeof(System.Object));
		L.RegFunction("Clear", Clear);
		L.RegFunction("Dispose", Dispose);
		L.RegFunction("New", _CreateSpine_Unity_MeshRendererBuffers_SmartMesh);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("mesh", get_mesh, set_mesh);
		L.RegVar("instructionUsed", get_instructionUsed, set_instructionUsed);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateSpine_Unity_MeshRendererBuffers_SmartMesh(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				Spine.Unity.MeshRendererBuffers.SmartMesh obj = new Spine.Unity.MeshRendererBuffers.SmartMesh();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Spine.Unity.MeshRendererBuffers.SmartMesh.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Clear(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Spine.Unity.MeshRendererBuffers.SmartMesh obj = (Spine.Unity.MeshRendererBuffers.SmartMesh)ToLua.CheckObject<Spine.Unity.MeshRendererBuffers.SmartMesh>(L, 1);
			obj.Clear();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Dispose(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Spine.Unity.MeshRendererBuffers.SmartMesh obj = (Spine.Unity.MeshRendererBuffers.SmartMesh)ToLua.CheckObject<Spine.Unity.MeshRendererBuffers.SmartMesh>(L, 1);
			obj.Dispose();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_mesh(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Spine.Unity.MeshRendererBuffers.SmartMesh obj = (Spine.Unity.MeshRendererBuffers.SmartMesh)o;
			UnityEngine.Mesh ret = obj.mesh;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index mesh on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_instructionUsed(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Spine.Unity.MeshRendererBuffers.SmartMesh obj = (Spine.Unity.MeshRendererBuffers.SmartMesh)o;
			Spine.Unity.SkeletonRendererInstruction ret = obj.instructionUsed;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index instructionUsed on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_mesh(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Spine.Unity.MeshRendererBuffers.SmartMesh obj = (Spine.Unity.MeshRendererBuffers.SmartMesh)o;
			UnityEngine.Mesh arg0 = (UnityEngine.Mesh)ToLua.CheckObject(L, 2, typeof(UnityEngine.Mesh));
			obj.mesh = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index mesh on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_instructionUsed(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Spine.Unity.MeshRendererBuffers.SmartMesh obj = (Spine.Unity.MeshRendererBuffers.SmartMesh)o;
			Spine.Unity.SkeletonRendererInstruction arg0 = (Spine.Unity.SkeletonRendererInstruction)ToLua.CheckObject<Spine.Unity.SkeletonRendererInstruction>(L, 2);
			obj.instructionUsed = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index instructionUsed on a nil value");
		}
	}
}

